dist: 'trusty'
language: node_js
sudo: required
node_js:
  - 'node'
  - '6.10.1'
services: 
  - redis-server
before_script:
  - npm install
  - npm run build
  - grunt candles:build
  - wget https://github.com/fiorix/freegeoip/releases/download/v3.1.5/freegeoip-3.1.5-linux-amd64.tar.gz
  - tar -zxvf freegeoip-3.1.5-linux-amd64.tar.gz
  - cd freegeoip-3.1.5-linux-amd64; ./freegeoip > /dev/null 2>&1 & cd ../
  - wget https://downloads.arise.io/arise/test/arise-Linux-x86_64.tar.gz
  - tar -zxf arise-Linux-x86_64.tar.gz
  - sudo service postgresql stop
  - cp test/config_arise.json arise-Linux-x86_64/config.json
  - cd arise-Linux-x86_64; bash arise.sh coldstart; cd ../
  - cp test/config.test ./config.js
  - node app.js &> /dev/null &
  - sleep 5
